In [1]:
import pandas as pd
a=pd.read_csv(r"D:\CODING\PYTHON\NLP\5.sms-spam-classifier-main\spam.csv",encoding="cp1252")
a

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [2]:
a=a.iloc[:,:-3]
a

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
import re
def remove_html(text):
    p=re.compile("<.?>")
    return p.sub(r"",text)

a["v2"]=a["v2"].apply(remove_html)

C:\Users\sinha\AppData\Local\Temp\ipykernel_34124\2570254999.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["v2"]=a["v2"].apply(remove_html)

In [4]:
a["v2"]=a["v2"].str.lower()
a

C:\Users\sinha\AppData\Local\Temp\ipykernel_34124\537626517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["v2"]=a["v2"].str.lower()

        v1                                                 v2
0      ham  go until jurong point, crazy.. available only ...
1      ham                      ok lar... joking wif u oni...
2     spam  free entry in 2 a wkly comp to win fa cup fina...
3      ham  u dun say so early hor... u c already then say...
4      ham  nah i don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  this is the 2nd time we have tried 2 contact u...
5568   ham              will ì_ b going to esplanade fr home?
5569   ham  pity, * was in mood for that. so...any other s...
5570   ham  the guy did some bitching but i acted like i'd...
5571   ham                         rofl. its true to its name

[5572 rows x 2 columns]

In [5]:
import string
pu=string.punctuation

def remove_punctuation(text):
    return text.translate(str.maketrans("","",pu))

a["v2"]=a["v2"].apply(remove_punctuation)
a

C:\Users\sinha\AppData\Local\Temp\ipykernel_34124\824923979.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["v2"]=a["v2"].apply(remove_punctuation)

        v1                                                 v2
0      ham  go until jurong point crazy available only in ...
1      ham                            ok lar joking wif u oni
2     spam  free entry in 2 a wkly comp to win fa cup fina...
3      ham        u dun say so early hor u c already then say
4      ham  nah i dont think he goes to usf he lives aroun...
...    ...                                                ...
5567  spam  this is the 2nd time we have tried 2 contact u...
5568   ham                will ì b going to esplanade fr home
5569   ham  pity  was in mood for that soany other suggest...
5570   ham  the guy did some bitching but i acted like id ...
5571   ham                          rofl its true to its name

[5572 rows x 2 columns]

In [6]:
from nltk.corpus import stopwords

def remove_stopword(text):
    new_text=[]
    for i in text.split():
        if i in stopwords.words("english"):
            new_text.append("")
        else:
            new_text.append(i)
    x=new_text[ : ]
    new_text.clear()
    return " ".join(x)

a["v2"]=a["v2"].apply(remove_stopword)

C:\Users\sinha\AppData\Local\Temp\ipykernel_34124\2698913552.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["v2"]=a["v2"].apply(remove_stopword)

In [7]:
a

        v1                                                 v2
0      ham  go  jurong point crazy available   bugis n gre...
1      ham                            ok lar joking wif u oni
2     spam  free entry  2  wkly comp  win fa cup final tkt...
3      ham              u dun say  early hor u c already  say
4      ham   nah  dont think  goes  usf  lives around  though
...    ...                                                ...
5567  spam     2nd time   tried 2 contact u u    å£750 pou...
5568   ham                       ì b going  esplanade fr home
5569   ham                   pity   mood   soany  suggestions
5570   ham   guy   bitching   acted like id  interested  b...
5571   ham                                  rofl  true   name

[5572 rows x 2 columns]

In [18]:
from sklearn.preprocessing import LabelEncoder

la=LabelEncoder()
y=la.fit_transform(a["v1"])
y

array([0, 0, 1, ..., 0, 0, 0])

In [20]:
from sklearn.feature_extraction.text import  TfidfVectorizer

tfidf=TfidfVectorizer()
x=tfidf.fit_transform(a["v2"]).toarray()
# x_test=tfidf.fit_transform(x_test).toarray()

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [23]:
from sklearn.ensemble import RandomForestClassifier
gnb=RandomForestClassifier()
gnb.fit(x_train,y_train)
gnb.score(x_test,y_test)*100

97.39910313901345